package com.upi.reconcile.connectors.crypto;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * PayU SHA-512 hash verifier for webhook response authentication.
 *
 * <p>PayU signs its webhook/callback POST body using SHA-512 (not HMAC).
 * The hash is computed over a pipe-delimited string of specific transaction
 * fields in <em>reverse</em> order compared to the payment request, with
 * the merchant salt prepended.
 *
 * <h3>Hash formula (reverse of payment request hash):</h3>
 * <pre>
 * SHA512(SALT|status||||||udf5|udf4|udf3|udf2|udf1|email|firstname|productinfo|amount|txnid|key)
 * </pre>
 *
 * <p>Empty fields (udf1–udf5, email, etc.) must still be represented as
 * empty strings between pipe delimiters.
 *
 * <p>Verification uses constant-time comparison to prevent timing attacks.
 *
 * @see <a href="https://devguide.payu.in/api/webhooks/">PayU Webhook Documentation</a>
 */
public final class PayuHashVerifier {

    private PayuHashVerifier() {
        // utility class
    }

    /**
     * Verifies the SHA-512 hash of a PayU webhook response.
     *
     * <p>Reconstructs the hash using the reverse pipe-delimited sequence:
     * {@code SHA512(salt|status||||||udf5|udf4|udf3|udf2|udf1|email|firstname|productinfo|amount|txnid|key)}
     *
     * @param key         the merchant key (from PayU dashboard)
     * @param salt        the merchant salt / api_secret (from PayU dashboard)
     * @param txnid       the transaction ID generated by the merchant system
     * @param amount      the transaction amount (as string, e.g. "100.00")
     * @param productinfo the product info string
     * @param firstname   the customer first name
     * @param email       the customer email
     * @param udf1        user-defined field 1 (empty string if not used)
     * @param udf2        user-defined field 2 (empty string if not used)
     * @param udf3        user-defined field 3 (empty string if not used)
     * @param udf4        user-defined field 4 (empty string if not used)
     * @param udf5        user-defined field 5 (empty string if not used)
     * @param status      the payment status from PayU (e.g. "success", "failure")
     * @param receivedHash the hash value received in the PayU webhook POST body
     * @return true if the hash matches; false if tampered or invalid
     */
    public static boolean verify(
            String key, String salt,
            String txnid, String amount, String productinfo,
            String firstname, String email,
            String udf1, String udf2, String udf3, String udf4, String udf5,
            String status,
            String receivedHash) {

        // Reverse pipe sequence: salt|status||||||udf5|udf4|udf3|udf2|udf1|email|firstname|productinfo|amount|txnid|key
        // The three empty pipes in the middle represent udf6, udf7, udf8, udf9, udf10 (rarely used)
        String hashString = String.join("|",
                salt,
                nvl(status),
                "",         // udf10
                "",         // udf9
                "",         // udf8
                "",         // udf7
                "",         // udf6
                nvl(udf5),
                nvl(udf4),
                nvl(udf3),
                nvl(udf2),
                nvl(udf1),
                nvl(email),
                nvl(firstname),
                nvl(productinfo),
                nvl(amount),
                nvl(txnid),
                nvl(key)
        );

        String computed = sha512Hex(hashString);
        // constant-time comparison
        return MessageDigest.isEqual(
                computed.getBytes(StandardCharsets.UTF_8),
                receivedHash.toLowerCase().getBytes(StandardCharsets.UTF_8)
        );
    }

    /** Computes lowercase hex SHA-512 of the input string (UTF-8). */
    public static String sha512Hex(String input) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-512");
            byte[] hash = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hash);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-512 not available", e);
        }
    }

    /** Returns the value, or empty string if null. */
    private static String nvl(String value) {
        return value != null ? value : "";
    }
}
